import type { SimulationEvent } from '@/stores/simulationStore';
import { products } from '@/data/products';

export function generateSimulationEvents(isFa: boolean): SimulationEvent[] {
  const events: SimulationEvent[] = [
    {
      id: 'se-01',
      time: '10:02 AM',
      type: 'customer-purchase',
      title: isFa ? 'خرید مشتری: ۳ عدد شیر کامل' : 'Customer bought 3 Whole Milk',
      description: isFa ? 'کاهش موجودی دسته WM-D001 به ۱۵ عدد' : 'Inventory updated for WM-D001 to 15 units',
      entityName: 'Whole Milk (2L)',
      impactValue: 1.55,
      units: 3,
    },
    {
      id: 'se-02',
      time: '10:05 AM',
      type: 'customer-purchase',
      title: isFa ? 'خرید مشتری: ۲ عدد ماست یونانی' : 'Customer bought 2 Greek Yogurt',
      description: isFa ? 'کاهش موجودی دسته GY-D101' : 'Batch GY-D101 inventory updated',
      entityName: 'Greek Yogurt (500g)',
      impactValue: 1.99,
      units: 2,
    },
    {
      id: 'se-03',
      time: '10:12 AM',
      type: 'low-stock-detected',
      title: isFa ? 'هشدار خودکار: تخم‌مرغ به آستانه کمبود رسید' : 'Low Stock Alert: Free Range Eggs',
      description: isFa ? 'تنها ۳ عدد باقی مانده (حداقل موجودی: ۱۲)' : 'Only 3 units remaining (Min stock: 12)',
      entityName: 'Free Range Eggs',
    },
    {
      id: 'se-04',
      time: '10:15 AM',
      type: 'expiry-workflow-triggered',
      title: isFa ? 'گردش‌کار انقضا اجرا شد: ماست یونانی' : 'Expiry Workflow Triggered: Greek Yogurt',
      description: isFa ? 'ایجاد خودکار عملیات بررسی تخفیف و اطلاع به مدیر' : 'Created discount review operation & notified manager',
      entityName: 'Expiry Protection Workflow',
    },
    {
      id: 'se-05',
      time: '10:20 AM',
      type: 'operation-assigned',
      title: isFa ? 'تخصیص عملیات: بررسی تخفیف ماست یونانی به سارا' : 'Operation Assigned: Review Greek Yogurt Discount',
      description: isFa ? 'مهلت انجام: امروز تا ساعت ۱۸:۰۰' : 'Due date set for today 18:00',
      entityName: 'Review Discount Operation',
    },
    {
      id: 'se-06',
      time: '10:28 AM',
      type: 'customer-purchase',
      title: isFa ? 'خرید مشتری: ۱ عدد پنیر چدار' : 'Customer bought 1 Mature Cheddar',
      description: isFa ? 'ثبت در سیستم فروش' : 'Recorded in POS system',
      entityName: 'Mature Cheddar',
      impactValue: 3.25,
      units: 1,
    },
    {
      id: 'se-07',
      time: '10:35 AM',
      type: 'purchase-approved',
      title: isFa ? 'درخواست خرید آبمیوه پرتقال تایید شد' : 'Purchase Request Approved: Orange Juice',
      description: isFa ? 'سفارش ۴۰ عدد از Greenfield Farms ثبت شد' : 'Order for 40 units submitted to Greenfield Farms',
      entityName: 'Orange Juice Request',
      impactValue: 44.0,
    },
    {
      id: 'se-08',
      time: '10:42 AM',
      type: 'discount-applied',
      title: isFa ? 'اعمال ۲۵٪ تخفیف روی دسته کرواسان' : 'Applied 25% Markdown on Croissants',
      description: isFa ? 'برچسب قیمت جدید فعال گردید' : 'New price labels activated',
      entityName: 'Butter Croissants',
    },
    {
      id: 'se-09',
      time: '10:50 AM',
      type: 'customer-purchase',
      title: isFa ? 'خرید مشتری: ۴ عدد فیله مرغ ارگانیک' : 'Customer bought 4 Organic Chicken Breast',
      description: isFa ? 'کاهش موجودی چیلر C1' : 'Chiller C1 inventory updated',
      entityName: 'Organic Chicken Breast',
      impactValue: 4.5,
      units: 4,
    },
    {
      id: 'se-10',
      time: '11:05 AM',
      type: 'supplier-delivery',
      title: isFa ? 'تحویل محموله جدید: نان تست تازه' : 'Supplier Delivery Received: Fresh Sourdough',
      description: isFa ? 'ورود ۱۵ عدد با تاریخ انقضای ۷ روزه' : 'Received 15 units with 7-day expiry',
      entityName: 'Artisan Sourdough',
    },
    {
      id: 'se-11',
      time: '11:15 AM',
      type: 'new-batch',
      title: isFa ? 'ثبت دسته جدید SD-D103 در سیستم' : 'Registered New Batch SD-D103',
      description: isFa ? 'بارکد و موقعیت قفسه اختصاص داده شد' : 'Barcode & shelf position allocated',
      entityName: 'Batch SD-D103',
    },
    {
      id: 'se-12',
      time: '11:30 AM',
      type: 'operation-completed',
      title: isFa ? 'تکمیل عملیات: جمع‌آوری اسفناج منقضی شده' : 'Operation Completed: Remove Expired Spinach',
      description: isFa ? '۲ عدد از قفسه خارج و در اتلاف ثبت شد' : '2 units removed & logged to waste',
      entityName: 'Remove Expired Spinach',
    },
    {
      id: 'se-13',
      time: '11:45 AM',
      type: 'customer-purchase',
      title: isFa ? 'خرید مشتری: ۲ عدد توت‌فرنگی تازه' : 'Customer bought 2 Strawberries',
      description: isFa ? 'ثبت فروش سریع' : 'Fast checkout recorded',
      entityName: 'Fresh Strawberries',
      impactValue: 2.2,
      units: 2,
    },
    {
      id: 'se-14',
      time: '12:00 PM',
      type: 'expiry-workflow-triggered',
      title: isFa ? 'گردش‌کار گوشت چرخ‌کرده اجرا شد' : 'Expiry Workflow Triggered: Beef Mince',
      description: isFa ? 'انقضا تا فردا — پیشنهاد اولویت‌دهی قفسه' : 'Expires tomorrow — shelf rotation alert',
      entityName: 'High Risk Expiry Workflow',
    },
    {
      id: 'se-15',
      time: '12:15 PM',
      type: 'customer-purchase',
      title: isFa ? 'خرید مشتری: ۳ عدد آبمیوه پرتقال' : 'Customer bought 3 Orange Juice',
      description: isFa ? 'فروش موفق' : 'Sales completed',
      entityName: 'Orange Juice',
      impactValue: 1.99,
      units: 3,
    },
  ];

  return events;
}
